### PR TITLE
debounce added

### PR DESCRIPTION
**Pull request by blackborn66**
I liked to prevent some db callbacks so I added the debouncing feature.

"Debouncing is a technique used to optimize application performance by reducing the rate at which functions are called."

Use it like that:
```
AwesompleteUtil.start('#user_combo',
  {
    url: 'json.php?search=',
    limit: -1,
    debounce: 300
  },
  {
    minChars: 3,
    maxItems: 8,
    data: function(rec, input) {
      return rec['last_name'];
    }
  }
)
```
without "debounce" it should work just like before

### CODE REVIEW

**Comment by blackborn66** [comment]
"debounce" is in milli seconds.

It's the waiting time after each keypress until a new lookup is started. If one hits multiple keys with less than the debounce time, the lookup is holding back while typing.

**Comment by nico-amsterdam** [comment]
Thanks for your pull request.
I will make a few changes when I pull it in.
- _AWE_TIMER is not a constant in your PR, and state should not be kept on the AwesompleteUtil object
- detachCopyFun should also call the clearTimeout
- I want to keep the same code style as the rest, even though it is has a really old school style
- documentation should be updated
- a new minimized version should be made

**Comment by blackborn66** [comment]
dat is helemaal prima!

**Review by nico-amsterdam — APPROVED** [review]

**Comment by nico-amsterdam** [comment]
Merged

**Pull request merged**
